<?php

/**
 * @file
 * Automatically make use of responsive images.
 */

use Drupal\responsive_image_automatic\Entity\ImageStyle;
use Drupal\Core\Template\Attribute;

/**
 * Implements hook_entity_type_build().
 */
function responsive_image_automatic_entity_type_build(&$entity_info) {
  // Replace the entity class for the Image Style entity type so that we can
  // control how images are generated and insert our own variants automatically.
  $entity_info['image_style']->setClass('Drupal\responsive_image_automatic\Entity\ImageStyle');
}

/**
 * Implements hook_theme_registry_alter().
 */
function responsive_image_automatic_theme_registry_alter(&$theme_registry) {
  // Don't use the core responsive image template because it relies on having
  // a responsive image entity.
  $module_path = \Drupal::service('extension.list.module')->getPath('responsive_image_automatic');
  $theme_registry['image_style']['path'] = $module_path . '/templates';
}

/**
 * Implements hook_preprocess_image_style().
 */
function responsive_image_automatic_preprocess_image_style(&$variables) {

  // The fallback image element.
  $variables['img_element'] = [
    '#theme' => 'image',
    '#srcset' => [
      [
        'uri' => $variables['image']['#uri'],
      ],
    ],
  ];

  $style = ImageStyle::load($variables['style_name']);
  $automatic_derivatives = $style->getAutomaticDerivativeUris($variables['image']['#uri']);
  ksort($automatic_derivatives);

  // Create sources for the picture element with each of the automatic
  // derivatives.
  foreach ($automatic_derivatives as $width => $automatic_derivative_uri) {
    $variables['sources'][] = new Attribute([
      'media' => '(max-width: ' . $width . 'px)',
      'srcset' => \Drupal::service('file_url_generator')->generateAbsoluteString($automatic_derivative_uri),
    ]);
  }

  // Ensure the polyfill is loaded for old browsers.
  $vars['#attached'] = [
    'library' => ['core/picturefill'],
  ];
}
